# local nav aliases
alias odin="cd ~/Dev/Odin-Project"
alias rails-book="cd ~/Dev/Odin-Project/rails-book"
alias flight-booker="cd ~/Dev/Odin-Project/flight-booker"
alias chess="cd ~/Dev/Odin-Project/Chess"
alias leet="cd ~/Dev/LeetCode"
alias advent="cd ~/Dev/Advent-of-Code"
alias ruby_ex="cd ~/snap/exercism/5/exercism/ruby"
alias kata-machine="~/Dev/kata-machine"
alias scratch="~/Dev/test-space"
