return {}
-- return {
--   { "JoshDevHub/dracula.nvim", branch = "vscode-colors" },
--   -- Configure LazyVim to load dracula
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "dracula",
--     },
--   },
-- }
